//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inteferente_ECO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inteferente_ECO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back1 {
            get {
                object obj = ResourceManager.GetObject("Back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back2 {
            get {
                object obj = ResourceManager.GetObject("Back2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back3 {
            get {
                object obj = ResourceManager.GetObject("Back3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back4 {
            get {
                object obj = ResourceManager.GetObject("Back4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back5 {
            get {
                object obj = ResourceManager.GetObject("Back5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deflector {
            get {
                object obj = ResourceManager.GetObject("Deflector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot 4 8
        ///Meduza1 2 6
        ///Meduza1 10 5
        ///Meduza2 7 6
        ///Meduza1 6 5
        ///Meduza2 14 8
        ///Meduza2 18 5
        ///Meduza2 12 8
        ///Meduza1 10 7
        ///Meduza2 2 2
        ///Sticla 9 3
        ///Sticla 7 3
        ///Hartie 4 5
        ///Hartie 10 5
        ///Plastic 14 3.
        /// </summary>
        internal static string Harta1 {
            get {
                return ResourceManager.GetString("Harta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot 1 8
        ///Meduza2 10 6
        ///Meduza2 10 5
        ///Meduza1 10 4
        ///Meduza3 10 3
        ///Meduza3 10 2
        ///Meduza1 10 1
        ///Meduza3 13 5
        ///Meduza2 14 5
        ///Meduza4 15 5
        ///Hartie 8 5
        ///Sticla 15 7
        ///Plastic 14 3.
        /// </summary>
        internal static string Harta2 {
            get {
                return ResourceManager.GetString("Harta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot 12 1
        ///Meduza1 5 6
        ///Meduza1 6 5
        ///Meduza4 7 5
        ///Meduza3 8 5
        ///Meduza3 9 5
        ///Meduza2 10 5
        ///Meduza4 10 6
        ///Meduza1 11 7
        ///Meduza2 11 8
        ///Meduza4 5 7
        ///Meduza3 15 5
        ///Meduza1 16 5
        ///Meduza2 17 5
        ///Meduza2 18 5
        ///Meduza1 14 5
        ///Meduza4 13 5
        ///Meduza1 13 6
        ///Meduza4 13 7
        ///Meduza3 13 8
        ///Meduza1 13 9
        ///Hartie 8 7
        ///Sticla 15 7
        ///Plastic 14 3.
        /// </summary>
        internal static string Harta3 {
            get {
                return ResourceManager.GetString("Harta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hartie {
            get {
                object obj = ResourceManager.GetObject("Hartie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Meduza1 {
            get {
                object obj = ResourceManager.GetObject("Meduza1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Meduza2 {
            get {
                object obj = ResourceManager.GetObject("Meduza2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Meduza3 {
            get {
                object obj = ResourceManager.GetObject("Meduza3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Meduza4 {
            get {
                object obj = ResourceManager.GetObject("Meduza4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plastic {
            get {
                object obj = ResourceManager.GetObject("Plastic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robot {
            get {
                object obj = ResourceManager.GetObject("Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sticla {
            get {
                object obj = ResourceManager.GetObject("Sticla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ioana eco
        ///Radu 123
        ///Maria abc
        ///Florin a
        ///Mihai tg.
        /// </summary>
        internal static string Useri {
            get {
                return ResourceManager.GetString("Useri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wood1 {
            get {
                object obj = ResourceManager.GetObject("Wood1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wood2 {
            get {
                object obj = ResourceManager.GetObject("Wood2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
